const athleteImages = [
  "Aaron_Long_Goalie_2008.jpg",
  "Alexander_Stewart_Forward_2008.jpg",
  "Beau_Brown_Forward_2008.jpg",
  "Benjamin_Cook_Forward_2008.jpg",
  "Bentley_Kelly_Forward_2008.jpg",
  "Brody_Ward_Defense_2008.jpg",
  "Caleb_Clark_Forward_2008.jpg",
  "Carson_Sanchez_Defense_2008.jpg",
  "Chase_Wilson_Forward_2008.jpg",
  "Cole_Adams_Forward_2009.jpg",
  "Connor_Hall_Forward_2008.jpg",
  "Dylan_Rogers_Defense_2008.jpg",
  "Easton_Collins_Forward_2007.jpg",
  "Easton_Hughes_Forward_2008.jpg",
  "Eli_Thompson_Defense_2008.jpg",
  "Emmett_Taylor_Defense_2008.jpg",
  "Ethan_Collins_Forward_2008.jpg",
  "Gavin_Walker_Forward_2008.jpg",
  "Grayson_Carter_Defense_2008.jpg",
  "Henry_Taylor_Forward_2008.jpg",
  "Hunter_Edwards_Defense_2009.jpg",
  "Isaac_Wright_Defense_2008.jpg",
  "Jackson_Roberts_Forward_2009.jpg",
  "James_Hayes_Forward_2008.jpg",
  "James_Parker_Forward_2007.jpg",
  "Jaxon_Baker_Goalie_2009.jpg",
  "Jude_Anderson_Defense_2008.jpg",
  "Jude_Wright_Goalie_2007.jpg",
  "Julian_Evans_Forward_2008.jpg",
  "Julian_Hill_Forward_2008.jpg",
  "Kai_Martin_Defense_2008.jpg",
  "Levi_Smith_Defense_2008.jpg",
  "Liam_Sanchez_Forward_2009.jpg",
  "Liam_Walker_Forward_2008.jpg",
  "Logan_Wilson_Defense_2008.jpg",
  "Lucas_White_Defense_2008.jpg",
  "Marcus_Carter_Forward_2008.jpg",
  "Mason_Bell_Defense_2009.jpg",
  "Miles_Cooper_Forward_2008.jpg",
  "Nicholas_Ludgate_Forward_2008.jpg",
  "Noah_Morris_Defense_2008.jpg",
  "Nolan_Miller_Forward_2008.jpg",
  "Owen_Green_Forward_2008.jpg",
  "Rowan_Phillips_Forward_2009.jpg",
  "Ryder_King_Forward_2009.jpg",
  "Sebastian_Reed_Forward_2008.jpg",
  "Theo_Moore_Forward_2008.jpg",
  "William_Davis_Forward_2008.jpg",
  "Wyatt_Butler_Forward_2008.jpg",
  "Xander_Turner_Forward_2008.jpg",
  "Zachary_Johnson_Forward_2008.jpg",
  "Jaxon_Baker_Stats.jpg",
  "emergent_heroshot01.jpg",
  "girl_globe.jpg",
  "Jaxon_Baker_Goalie_2009.jpg",
  "Marcus_Carter_Forward_2008.jpg",
  "Nicholas_Ludgate_Forward_2008.jpg",
  "Owen_Green_Forward_2008.jpg",
  "bg_banner.jpg",
  "bg_banner_girl_globe_etsports.png",
  "L-447 copy_shadow copy.png",
  "Letterhead_logo copy.png",
  "Letterhead_logo_final.png",
  "logo.png",
  "logo_banner_premium copy.png",
  "logo_ETv.gif",
  "logo_ETv.png",
  "logo_premium copy 32x32.png",
  "logo_premium copy.png",
  "Logo_Premium_wCoName copy.png",
  "Logo_Premium_wCoName_062310 copy.png",
  "Logo_Premium_wCoName_250x250.png",
  "Logo_Premium_wCoName_41x41.png",
  "Logo_Premium_wCoName_80x80_facebook.png",
  "main_top.jpg",
  "MediaPortal.png",
  "MediaPortal_64H.png",
  "Media_Portal_2.png",
  "Media_Portal_copy.png",
  "signature_logo copy.png",
];
